(define-datatype vector ((element type)) ((length nat))
  (null-vector (vector element zero))
  (cons-vector ((implicit prev nat)
                (head element)
                (tail (vector element prev)))
               (vector element (add1 prev))))
